all:
    # install faster_rcnn locally
	python3 setup.py build_ext --inplace
	rm -rf build

install:
	# install faster_rcnn to the Python site-packages
	python3 setup.py build_ext install
	rm -rf build